version: 2

aliases:
    - &restore_cache
        keys:
            - cget-{{ arch }}-{{ checksum "native_requirements.txt" }}
    - &install_dependencies
        name: Install C++ Dependencies
        command: ./init.sh
    - &save_cache
        key:
            cget-{{ arch }}-{{ checksum "native_requirements.txt" }}
        paths:
            - "cget"
    - &run-test-with-coverage
        name: "Run Tests"
        command: |
            rm -fr build
            rm -fr dist
            $PYTHON_PATH/python setup.py install
            $PYTHON_PATH/pip install coverage
            cd tests
            $PYTHON_PATH/coverage run tests.py
            bash <(curl -s https://codecov.io/bash) -t 2a289a72-91f5-4a4c-b011-fc9288666a49
    - &update_ld_library_path
        name: "Update Library Search Path"
        command: echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/cget/lib:$(pwd)/cget/lib64' >> $BASH_ENV
    - &test-suite-linux-template
        docker:
            - image: peymanmo/many_x64
        steps:
            - checkout
            - restore_cache: *restore_cache
            - run: *install_dependencies
            - save_cache: *save_cache
            - run: *update_ld_library_path
            - run: *run-test-with-coverage
    - &mac-create-virtualenv
        name: "Create Virtual Environment"
        command: |
            virtualenv -p $PYTHON_BIN venv
            echo source $(pwd)/venv/bin/activate >> $BASH_ENV
            echo 'export PYTHON_PATH=$(pwd)/venv/bin' >> $BASH_ENV
    - &mac-install-requirements
        name: "Install Development Tools"
        command: pip install -r requirements.txt
    - &create-pypi-auth
        name: 'Add PyPI Authentication File'
        command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

jobs:
    lint-checks:
        docker:
            - image: circleci/python:2.7.13
        steps:
            - checkout
            - run:
                name: Setup Virtual Environment
                command: virtualenv venv
            - run:
                name: Install Flake8
                command: |
                    source venv/bin/activate
                    pip install flake8
                    pip install flake8-import-order
            - run:
                name: Flake8 Check
                command: |
                    source venv/bin/activate
                    flake8 garlicconfig

    test-linux-py27m:
        environment:
            PYTHON_PATH: /opt/python/cp27-cp27m/bin
        <<: *test-suite-linux-template

    test-linux-py27mu:
        environment:
            PYTHON_PATH: /opt/python/cp27-cp27mu/bin
        <<: *test-suite-linux-template

    test-linux-py34m:
        environment:
            PYTHON_PATH: /opt/python/cp34-cp34m/bin
        <<: *test-suite-linux-template

    test-linux-py35m:
        environment:
            PYTHON_PATH: /opt/python/cp35-cp35m/bin
        <<: *test-suite-linux-template

    test-linux-py36m:
        environment:
            PYTHON_PATH: /opt/python/cp36-cp36m/bin
        <<: *test-suite-linux-template

    test-linux-py37m:
        environment:
            PYTHON_PATH: /opt/python/cp37-cp37m/bin
        <<: *test-suite-linux-template

    dist-linux:
        docker:
            - image: peymanmo/many_x64
        steps:
            - checkout
            - restore_cache: *restore_cache
            - run: *install_dependencies
            - save_cache: *save_cache
            - run:
                name: 'Build Wheel Packages'
                command: ./.circleci/dist-linux.sh
            - run: *create-pypi-auth
            - run:
                name: 'Twine :: Upload to PyPI'
                environment:
                    PYTHON_PATH: /opt/python/cp37-cp37m/bin
                command: |
                    $PYTHON_PATH/pip install twine
                    $PYTHON_PATH/twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*

    test-mac-py27: &test-mac-template
        macos:
            xcode: "10.0.0"
        environment:
            PYTHON_BIN: python
        steps:
            - checkout
            - run: *mac-create-virtualenv
            - run: *mac-install-requirements
            - restore_cache: *restore_cache
            - run: *install_dependencies
            - save_cache: *save_cache
            - run: *run-test-with-coverage

    test-mac-py37:
        <<: *test-mac-template
        environment:
            PYTHON_BIN: python3

    dist-mac-py27: &dist-mac-template
        macos:
            xcode: "10.0.0"
        environment:
            PYTHON_BIN: python
        steps:
            - checkout
            - run: *mac-create-virtualenv
            - run: *mac-install-requirements
            - restore_cache: *restore_cache
            - run: *install_dependencies
            - save_cache: *save_cache
            - run:
                name: 'Build Wheel Package'
                command: $PYTHON_PATH/python setup.py bdist_wheel
            - run: *create-pypi-auth
            - run:
                name: 'Twine :: Upload to PyPI'
                command: |
                    $PYTHON_PATH/pip install twine
                    $PYTHON_PATH/twine upload --repository-url https://test.pypi.org/legacy/ dist/*

    dist-mac-py37:
        <<: *dist-mac-template
        environment:
            PYTHON_BIN: python3

workflows:
    version: 2
    pr-checks:
        jobs:
            - lint-checks
            - test-linux-py27m
            - test-linux-py27mu
            - test-linux-py34m
            - test-linux-py35m
            - test-linux-py36m
            - test-linux-py37m
            - test-mac-py27
            - test-mac-py37
    dist:
        jobs:
            - dist-linux:
                filters:
                    tags:
                        only: /[0-9][.][0-9][.][0-9]/
            - dist-mac-py27:
                filters:
                    tags:
                        only: /[0-9][.][0-9][.][0-9]/
            - dist-mac-py37:
                filters:
                    tags:
                        only: /[0-9][.][0-9][.][0-9]/
