version: 2

aliases:
    - &restore_cache
        keys:
            - cget-{{ arch }}-{{ checksum "native_requirements.txt" }}
    - &install_dependencies
        name: Install C++ Dependencies
        command: ./init.sh
    - &save_cache
        key:
            cget-{{ arch }}-{{ checksum "native_requirements.txt" }}
        paths:
            - "cget"
    - &run-test
        command: |
            rm -fr build
            rm -fr dist
            $PYTHON_PATH/python setup.py install
            $PYTHON_PATH/python tests/tests.py
    - &run-test-with-coverage
        command: |
            rm -fr build
            rm -fr dist
            $PYTHON_PATH/python setup.py install
            $PYTHON_PATH/pip install coverage
            $PYTHON_PATH/coverage run tests/tests.py
            bash <(curl -s https://codecov.io/bash) -t 2a289a72-91f5-4a4c-b011-fc9288666a49

jobs:
    lint-checks:
        docker:
            - image: circleci/python:2.7.13
        steps:
            - checkout
            - run:
                name: Setup Virtual Environment
                command: virtualenv venv
            - run:
                name: Install Flake8
                command: |
                    source venv/bin/activate
                    pip install flake8
                    pip install flake8-import-order
            - run:
                name: Flake8 Check
                command: |
                    source venv/bin/activate
                    flake8 garlicconfig

    test-suite-linux:
        docker:
            - image: peymanmo/many_x64
        steps:
            - checkout
            - restore_cache: *restore_cache
            - run: *install_dependencies
            - save_cache: *save_cache
            - run:
                <<: *run-test
                name: "Test :: Python 2.7 M"
                environment:
                    PYTHON_PATH: /opt/python/cp27-cp27m/bin/
            - run:
                <<: *run-test
                name: "Test :: Python 2.7 M (Unicode)"
                environment:
                    PYTHON_PATH: /opt/python/cp27-cp27mu/bin/
            - run:
                <<: *run-test
                name: "Test :: Python 3.4 M"
                environment:
                    PYTHON_PATH: /opt/python/cp34-cp34m/bin/
            - run:
                <<: *run-test
                name: "Test :: Python 3.5 M"
                environment:
                    PYTHON_PATH: /opt/python/cp35-cp35m/bin/
            - run:
                <<: *run-test
                name: "Test :: Python 3.6 M"
                environment:
                    PYTHON_PATH: /opt/python/cp36-cp36m/bin/
            - run:
                <<: *run-test-with-coverage
                name: "Test :: Python 3.7 M"
                environment:
                    PYTHON_PATH: /opt/python/cp37-cp37m/bin/

workflows:
    version: 2
    pr-checks:
        jobs:
            - test-suite-linux
            - lint-checks
