name: PR Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install flake8 flake8-import-order
          flake8 garlicconfig

  test-linux:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ./init.sh
          export CURRENT_DIR=$(pwd)
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURRENT_DIR/cget/lib:$CURRENT_DIR/cget/lib64
      - name: Run Tests
        run: |
          rm -rf build dist
          export CURRENT_DIR=$(pwd)
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURRENT_DIR/cget/lib:$CURRENT_DIR/cget/lib64
          python setup.py install
          cd tests
          python tests.py
      - name: Upload to Coveralls
        run: |
          pip install coveralls
          coveralls



  test-mac:
    strategy:
      matrix:
        python-version: ['3.9']
    runs-on: macos-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create Virtual Environment and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install scikit-build
          pip install -r requirements.txt
          ./init.sh
          export CURRENT_DIR=$(pwd)
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURRENT_DIR/cget/lib:$CURRENT_DIR/cget/lib64
      - name: Install Garlicconfig # error in ghactions
        run: |
          source venv/bin/activate
          pip install -e .
      - name: Run Tests
        run: |
          rm -rf build dist
          source venv/bin/activate
          export CURRENT_DIR=$(pwd)
          export CGET_PATH=$CURRENT_DIR/cget
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURRENT_DIR/cget/lib:$CURRENT_DIR/cget/lib64
          python setup.py install
          cd tests
          python tests.py
      - name: Upload to Coveralls
        run: |
          source venv/bin/activate
          pip install coveralls
          coveralls
